<h2>Members</h2>

<?php
echo $this->errors ? $this->formErrors($this->errors) : '';

$this->form->setAction($this->url());
echo $this->form;
?>

<table>
<tbody>
<?php if(!empty($this->rows)) : $row = $this->rows[0]; ?>
<tr>
<?php foreach ($row as $key => $value) : ?><td><?php if($key == 'id') : echo 'View'; else : echo ucwords(str_replace("_", " ", $key)); endif; ?></td><?php endforeach; ?>
<td>Add Friend</td>
</tr>
<?php foreach ($this->rows as $row) : ?>
<tr>
<?php foreach ($row as $key => $value) : ?><td><?php if($key == 'id') :?><a href="<?php echo $this->baseUrl() . '/member/view/id/' . $value; ?>">View</a> <?php else : echo $value; endif; ?></td><?php endforeach; ?>
<td><a href="<?php echo $this->baseUrl() . '/friend/add/id/' . $row['id']; ?>">Add Friend</a></td>
</tr>
<?php endforeach; else : echo '<p>No member with that name found. Try another.</p>'; endif; ?>
</tbody>
</table>

<p><a href="<?php echo $this->url(array('action' => 'index', 'controller' => 'friend')) ?>/">View Friends</a></p>

<p>Return to <a href="<?php echo $this->baseUrl() . "/dashboard/"; ?>">Dashboard</a></p>
