  <footer>
  <p>Pages</p>
  <ul>
  	<li><a href="<?php echo $this->baseUrl() . "/auth/register"; ?>">Sign-Up</a></li>
  	<li><a href="<?php echo $this->baseUrl() . "/index/privacy"; ?>">Privacy</a></li>
  	<li><a href="<?php echo $this->baseUrl() . "/index/terms"; ?>">T & C</a></li>
  	<li><a href="<?php echo $this->baseUrl() . "/index/contact"; ?>">Contact</a></li>
  	<li><a href="<?php echo $this->baseUrl() . "/index/faqs"; ?>">FAQs</a></li>
  	<li><a href="<?php echo $this->baseUrl() . "/index/donations"; ?>">Donation</a></li>
  </ul>
    <p>&copy; Capstone Capital Pte Ltd.</p>    
  </footer>