<p>CEO Speaks</p> 
<p>Welcome to winsandwants.com.</p> 
<p>winsandwants.com helps you to develop the habit of setting goals and reviewing your goals everyday.  The beautiful thing about it is that it helps you share your goals with your family members, friends, co-workers or even your MasterMind groups.</p> 
<p>Make winsandwants.com your landing page on your web browser and make it a habit to set your goals believing you can achieve them everyday.  Make it also a habit to review your achievement with an attitude of gratitude.  By sharing your wins and wants, you are making a commitment to achieve the goals. You are also attracting the right energy and resources that will help you achieve these goals.</p> 
<p>This service is available to you absolutely free. Please share it with your family and loved ones, friends and colleagues.</p> 
<p>Michael Ong<br /> 
Chief Executive Officer<br /> 
winsandwants.com</p> 

<p><strong>Tell your friends about the website!</strong></p> 
<form id="form1" method="post" action=""> 
<label for="emails">Share This With:</label><br /> 
<textarea id="emails" name="emails" rows="2" cols="65" /></textarea> 
<p class="smalltext">Enter email addresses of people you want to share this  with.  Insert a comma between email  addresses.</p> 
<input type="submit" name="submit" value="Submit" />
<?php echo "<p class='message'>" . $this->msg . "</p>"; ?>
</form> 
<p><strong>PS:</strong></p> 
<p>If you wish to contribute to the success and continual development of this website, you can make a small contribution via PAYPAL to <a href="mailto:contributions@winsandwants.com">contributions@winsandwants.com</a>.</p> 
<p>If you have any suggestion for the improvement of the website, please drop us a note to <a href="mailto:suggestions@winsandwants.com">suggestions@winsandwants.com</a>.</p> 
<p><a href="<?php echo $this->baseUrl() . "/wins-and-wants/add"; ?>">Go to winsandwants Template</a></p> 