<p>Q1: What is Wins and Wants?</p> 
<p>A1: Wins and Wants is a web site that encourages individuals into a habit of setting goals on a daily basis. It also allows you to express your wants and through our network of subscribers, winsandwants.com, could connect you to other like-minded people, who could offer you directions and or solutions on how you could possibly achieve your wants</p> 
<p>Q2: Why Use Wins and Wants?</p> 
<p>A2: It engenders a forming habit discipline of recording your goals for the day, as opposed to just thinking about it. It makes you more committed towards achieving the goals you have set</p> 
<p>Q3: How Do I Go About Using Wins and Wants?</p> 
<p>A3: Please visit the tab where the full instructions on "How To Use" is described (Link To Tab)</p> 
<p>Q4: When Should I Use Wins and Wants?</p> 
<p>A4: It is highly recommended that you use Wins and Wants on a daily basis. Having daily goals, provides you with a sense of direction, purpose and achievement, when you see accomplishments to the goals you had set</p> 
<p>Q5: How would the confidentiality of my information, such as my set goals, be protected?</p> 
<p>A5: Please visit the tab "Privacy Policy" where we describe how the information you have provided to us is protected (Link to Tab)</p> 
<p>Q6: How do I go about forming a MasterMind group?</p> 
<p>A6: Please visit the tab where the full instructions on "MasterMind" is described (Link To Tab)</p> 
<p>Q7: Who can I turn to for assistance, should I have difficulty forming and running my MasterMind group?</p> 
<p>A7: Please forward your request for assistance to suggestions@winsandwants.com</p> 
<p>Q8: Why is it necessary to donate to the Wins and Wants web site?</p> 
<p>A8: Although, Wins and Wants is free-to-use, the site has to be periodically maintained, to ensure its functional qualities meet your expectations</p> 
<p>Q9: How will my donation be used?</p> 
<p>A9: Your donation will go towards the updating and upgrading of this web site. We, your providers, will keep this site fresh and lively, always ensuring that you our users, will continue to have a trouble-free and enjoyable user-friendly experience. You are also encouraged to offer us suggestions on how we could further improve this web site. Your suggestions should be sent to suggestions@winsandwants.com</p> 
<p>Q10: How do I make a donation?</p> 
<p>A10: Please visit the tab, "Donation" and followed the link provided (Link to Tab)</p> 