<p>At winsandwants.com we respect the privacy of all of our users and are committed to providing a safe, trusted and reliable service for them</p> 
<p>We do not use any personal information such as names, email addresses etc. for any purpose that may violate a user's privacy</p> 
<p>We will not send any unsolicited email or contact any of our users unless they ask us to, or unless there is an urgent problem that we need to resolve</p> 
<p>We do not use spyware, adware or trojan software in winsandwants.com</p> 
<p>We do not send any personal information about you or your computer once you become a user of the winsandwants.com site</p> 
<p>We may collect IP addresses and browser information for our own logging purposes and to help us improve our services.  However we will not share any of this information with any other party unless required to by law.</p> 