<h2>Dashboard</h2>

<fieldset class="panel"><legend>Goals</legend>
<p><a href="<?php echo $this->url(array('action' => 'index', 'controller' => 'goal')) ?>/">Goals</a></p>
<p><a href="<?php echo $this->url(array('action' => 'add', 'controller' => 'goal')) ?>/">Add Goal</a></p>
</fieldset>

<fieldset class="panel"><legend>Friends</legend>
<p><a href="<?php echo $this->url(array('action' => 'index', 'controller' => 'friend')) ?>/">Friends</a></p>
<p><a href="<?php echo $this->url(array('action' => 'find', 'controller' => 'member')) ?>/">Find Friends</a></p>
<p><a href="<?php echo $this->url(array('action' => 'request', 'controller' => 'friend')) ?>/">Friend Requests</a></p>
</fieldset>
