<footer class="wrapper">
	<small>Copyright &copy; Capstone Capital Pte Ltd</small>
	<nav>
		<ul>
			<li><a href="<?php echo $this->baseUrl() . "/auth/register"; ?>">Sign-Up</a></li>
			<li><a href="<?php echo $this->baseUrl() . "/index/privacy"; ?>">Privacy</a></li>
			<li><a href="<?php echo $this->baseUrl() . "/index/terms"; ?>">T & C</a></li>
			<li><a href="<?php echo $this->baseUrl() . "/index/contact"; ?>">Contact</a></li>
			<li><a href="<?php echo $this->baseUrl() . "/index/faqs"; ?>">FAQs</a></li>
			<li><a href="<?php echo $this->baseUrl() . "/index/donations"; ?>">Donation</a></li>
		</ul>
	</nav>
</footer>
