<?php echo $this->doctype() . "\n"; ?>
<html lang=en>
<head>
<?php echo $this->headTitle() . "\n"; ?>
<meta charset=utf-8>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . '/css/superfish.css'); ?>
<?php echo $this->headLink() . "\n"; ?>
<?php 
$this->headScript()->appendFile($this->baseUrl() . '/js/superfish.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/supersubs.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/nav.js');
?>
<?php echo $this->headScript() . "\n"; ?>
<!--[if lt IE 9]>
<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
</head>
<body>
<div class="container">

  <?php echo $this->render('header.phtml') ?>
  
  <?php echo $this->render('sidebar.phtml') ?>
  
  <div id="content">
  <?php echo $this->layout()->content; ?>
  </div>
  
  <?php echo $this->render('footer.phtml') ?>
  	
<!-- end .container --></div>
</body>
</html>

