<?php 

$auth = Zend_Auth::getInstance();
if($auth->hasIdentity()):
$identity = $auth->getIdentity();
?>
<p>Welcome <?php echo $identity->name; ?> <a
	href="<?php echo $this->url(array('action' => 'logout', 'controller' => 'auth')); ?>">Logout</a></p>
<p>Settings</p>	
<ul>
	<li><a href="<?php echo $this->url(array('action' => 'update', 'controller' => 'auth')); ?>">Password</a></li>
	<li><a href="<?php echo $this->url(array('action' => 'index', 'controller' => 'profile')); ?>">Profile</a></li>
</ul>
<?php
else :
?>
<p><a
	href="<?php echo $this->url(array('action' => 'login', 'controller' => 'auth')); ?>">Login</a>
or <a
	href="<?php echo $this->url(array('action' => 'register', 'controller' => 'auth')); ?>">Sign-Up</a></p>
<?php
endif;
?> 