<?php 

$auth = Zend_Auth::getInstance();
if($auth->hasIdentity()):
	$identity = $auth->getIdentity();
?>
<nav>
<ul class="sf-menu">
	<li class="current"><a href="<?php echo $this->baseUrl() . "/dashboard"; ?>">Dashboard</a></li>
	<li><a href="<?php echo $this->baseUrl() . "/index/ceospeaks"; ?>">CEO
	Speaks</a></li>
	<li><a href="<?php echo $this->baseUrl() . "/index/goalsetting"; ?>">Goal
	Setting</a>
	<ul>
		<li><a href="<?php echo $this->baseUrl() . "/index/use"; ?>">How To
		Use winsandwants Template</a></li>
	</ul>
	</li>
	<li><a
		href="<?php echo $this->baseUrl() . "/index/mastermind-principle"; ?>">MasterMind
	Principle</a>
	<ul>
		<li><a href="<?php echo $this->baseUrl() . "/index/guidelines"; ?>">MasterMind
		Guidelines</a></li>
		<li><a href="<?php echo $this->baseUrl() . "/index/purchase"; ?>">Purchase
		"Think And Grow Rich"</a></li>
	</ul>
	</li>
</ul>
</nav>
<?php
else :
?> 
<nav>
<ul class="sf-menu">
	<li class="current"><a href="<?php echo $this->baseUrl() . "/"; ?>">Home</a></li>
	<li><a href="<?php echo $this->baseUrl() . "/index/ceospeaks"; ?>">CEO
	Speaks</a></li>
	<li><a href="<?php echo $this->baseUrl() . "/index/goalsetting"; ?>">Goal
	Setting</a>
	<ul>
		<li><a href="<?php echo $this->baseUrl() . "/index/use"; ?>">How To
		Use winsandwants Template</a></li>
	</ul>
	</li>
	<li><a
		href="<?php echo $this->baseUrl() . "/index/mastermind-principle"; ?>">MasterMind
	Principle</a>
	<ul>
		<li><a href="<?php echo $this->baseUrl() . "/index/guidelines"; ?>">MasterMind
		Guidelines</a></li>
		<li><a href="<?php echo $this->baseUrl() . "/index/purchase"; ?>">Purchase
		"Think And Grow Rich"</a></li>
	</ul>
	</li>
</ul>
</nav>
<?php
endif;
?> 