<?php $this->headLink()->appendStylesheet($this->baseUrl() . '/css/winstable.css'); ?>

<h2>Your winsandwants.</h2>

<table border="1" id='hor-minimalist-b'>
  <tr>
    <th scope="row">Id</th>
    <td><?php echo $this->wins->getId(); ?></td>
  </tr>
  <tr>
    <th scope="row">Created</th>
    <td><?php echo $this->wins->getCreated(); ?></td>
  </tr>
  <tr>
    <th scope="row">Wins 01</th>
    <td><?php echo $this->wins->getWins01(); ?></td>
  </tr>
  <tr>
    <th scope="row">Wins 02</th>
    <td><?php echo $this->wins->getWins02(); ?></td>
  </tr>
  <tr>
    <th scope="row">Wins 03</th>
    <td><?php echo $this->wins->getWins03(); ?></td>
  </tr>
  <tr>
    <th scope="row">Wins 04</th>
    <td><?php echo $this->wins->getWins04(); ?></td>
  </tr>
  <tr>
    <th scope="row">Wins 05</th>
    <td><?php echo $this->wins->getWins05(); ?></td>
  </tr>
  <tr>
    <th scope="row">Wants 01</th>
    <td><?php echo $this->wins->getWants01(); ?></td>
  </tr>
  <tr>
    <th scope="row">Wants 02</th>
    <td><?php echo $this->wins->getWants02(); ?></td>
  </tr>
  <tr>
    <th scope="row">Wants 03</th>
    <td><?php echo $this->wins->getWants03(); ?></td>
  </tr>
  <tr>
    <th scope="row">Wants 04</th>
    <td><?php echo $this->wins->getWants04(); ?></td>
  </tr>
  <tr>
    <th scope="row">Wants 05</th>
    <td><?php echo $this->wins->getWants05(); ?></td>
  </tr>
  <tr>
    <th scope="row">Emails</th>
    <td><?php echo $this->wins->getEmails(); ?></td>
  </tr>
  <tr>
    <th scope="row">User Id</th>
    <td><?php echo $this->wins->getUserId(); ?></td>
  </tr>
</table>

<p>Return to <a href="<?php echo $this->baseUrl() . "/wins-and-wants/list"; ?>">List</a></p>
