<?php $this->headLink()->appendStylesheet($this->baseUrl() . '/css/winstable.css'); ?>

<h2>Your winsandwants has been saved.</h2>
<p>Below is your recently saved data:</p>

<table border="1" id='hor-minimalist-b'>
  <tr>
    <th scope="row">Id</th>
    <td><?php echo $this->wins->data['id']; ?></td>
  </tr>
  <tr>
    <th scope="row">Created</th>
    <td><?php echo $this->wins->data['created']; ?></td>
  </tr>
  <tr>
    <th scope="row">Wins 01</th>
    <td><?php echo $this->wins->data['wins_01']; ?></td>
  </tr>
  <tr>
    <th scope="row">Wins 02</th>
    <td><?php echo $this->wins->data['wins_02']; ?></td>
  </tr>
  <tr>
    <th scope="row">Wins 03</th>
    <td><?php echo $this->wins->data['wins_03']; ?></td>
  </tr>
  <tr>
    <th scope="row">Wins 04</th>
    <td><?php echo $this->wins->data['wins_04']; ?></td>
  </tr>
  <tr>
    <th scope="row">Wins 05</th>
    <td><?php echo $this->wins->data['wins_05']; ?></td>
  </tr>
  <tr>
    <th scope="row">Wants 01</th>
    <td><?php echo $this->wins->data['wants_01']; ?></td>
  </tr>
  <tr>
    <th scope="row">Wants 02</th>
    <td><?php echo $this->wins->data['wants_02']; ?></td>
  </tr>
  <tr>
    <th scope="row">Wants 03</th>
    <td><?php echo $this->wins->data['wants_03']; ?></td>
  </tr>
  <tr>
    <th scope="row">Wants 04</th>
    <td><?php echo $this->wins->data['wants_04']; ?></td>
  </tr>
  <tr>
    <th scope="row">Wants 05</th>
    <td><?php echo $this->wins->data['wants_05']; ?></td>
  </tr>
  <tr>
    <th scope="row">User Id</th>
    <td><?php echo $this->wins->data['user_id']; ?></td>
  </tr>
</table>



<p>Return to <a href="<?php echo $this->baseUrl() . "/dashboard/"; ?>">dashboard</a></p>

